version: "3.8"
services:
  backend:
    build: ./backend
    container_name: kyc-backend
    ports:
      - "9100:9100"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/kyc_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - app_network

    volumes:
      - ./uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: kyc-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge