name: nexacore
services:
  nexacore-backend:
    build: ./backend
    container_name: nexacore-backend
    ports:
      - "9100:9100"
    environment:
      SPRING_DATASOURCE_AUTH_JDBC_URL: jdbc:postgresql://host.docker.internal:5433/auth_db
      SPRING_DATASOURCE_AUTH_USERNAME: postgres
      SPRING_DATASOURCE_AUTH_PASSWORD: 123456
      SPRING_DATASOURCE_AUTH_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_KYC_JDBC_URL: jdbc:postgresql://host.docker.internal:5433/kyc_db
      SPRING_DATASOURCE_KYC_USERNAME: postgres
      SPRING_DATASOURCE_KYC_PASSWORD: 123456
      SPRING_DATASOURCE_KYC_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_GIS_JDBC_URL: jdbc:postgresql://host.docker.internal:5433/gisdb
      SPRING_DATASOURCE_GIS_USERNAME: postgres
      SPRING_DATASOURCE_GIS_PASSWORD: 123456
      SPRING_DATASOURCE_GIS_DRIVER_CLASS_NAME: org.postgresql.Driver
      STORAGE_TYPE: minio
      MINIO_ENDPOINT: http://host.docker.internal:9000
      MINIO_PUBLIC_BASE_URL: http://localhost:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: kyc-files
      AUTH_MODE: ${AUTH_MODE:-LOCAL}
      KEYCLOAK_ISSUER_URI: http://localhost:9200/realms/kyc
      KEYCLOAK_JWK_SET_URI: http://host.docker.internal:9200/realms/kyc/protocol/openid-connect/certs
      KEYCLOAK_CLIENT_ID: nexacore-client
      KEYCLOAK_AUDIENCE: nexacore
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./uploads:/opt/nexacore/uploads

  nexacore-frontend:
    build: ./frontend
    container_name: nexacore-frontend
    ports:
      - "4200:80"
    depends_on:
      - nexacore-backend
    networks:
      - app_network

  nexacore-privilege-frontend:
    build: ./privilege-frontend
    container_name: nexacore-privilege-frontend
    ports:
      - "4300:80"
    depends_on:
      - nexacore-backend
    networks:
      - app_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: nexacore-keycloak
    command:
      - start-dev
      - --http-port=9200
      - --db=postgres
      - --db-url=jdbc:postgresql://host.docker.internal:5433/kyc_db?currentSchema=keycloak
      - --db-username=postgres
      - --db-password=123456
    ports:
      - "9200:9200"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app_network:
    driver: bridge
